
[milestones]
#Number of hearts you start out with.
#Range: 0 ~ 1000
baseHearts = 10
#Number of hearts you gain for reaching a new milestone.
#Range: 0 ~ 1000
heartsPerMilestone = 1
#A list of numbers of unique foods you need to eat to unlock each milestone, in ascending order. Naturally, adding more milestones lets you earn more hearts.
milestones = [
	10,
	20,
	30,
	40,
	50,
	60,
	70,
	80,
	90,
	100,
	110,
	120,
	130,
	140,
	150,
	160,
	170,
	180,
	190,
	200,
	210,
	220,
	230,
	240,
	250,
	260,
	270,
	280,
	290,
	300,
	310,
	320,
	330,
	340,
	350,
	360,
	370,
	380,
	390,
	400,
	410,
	420,
	430,
	440,
	450,
	460,
	470,
	480,
	490,
	500,
	510,
	520,
	530,
	540,
	550,
	560,
	570,
	580,
	590,
	600,
	610,
	620,
	630,
	640,
	650,
	660,
	670,
	680,
	690,
	700
]

[filtering]
#Foods in this list won't affect the player's health nor show up in the food book.
blacklist = ['avaritia:cosmic_meatballs', 'croptopia:fried_frog_legs', 'croptopia:frog_legs', 'delightful:chopped_clover', 'delightful:chunkwich', 'tconstruct:bacon', 'hexerei:milk_bottle', 'hexerei:quicksilver_bottle', 'forbidden_arcanus:edelwood_suspicious_stew_bucket', 'tombstone:easter_egg_food', 'tombstone:easter_egg']
#When this list contains anything, the blacklist is ignored and instead only foods from here count.
whitelist = []
#The minimum hunger value foods need to provide in order to count for milestones, in half drumsticks.
#Range: 0 ~ 1000
minimumFoodValue = 1

[miscellaneous]
#Whether or not to reset the food list on death, effectively losing all bonus hearts.
resetOnDeath = false
#If true, eating foods outside of survival mode (e.g. creative/adventure) is not tracked and thus does not contribute towards progression.
limitProgressionToSurvival = false
